name: "Build frozen app"
description: "Builds the app with PyInstaller, zips it and uploads it as artifact"
inputs:
  frozen-archive-name:
    description: "Name of the zip file to be created and published that contains the frozen application"
    default: "release.zip"
runs:
  using: "composite"
  steps:
    - name: Setup Python version
      uses: actions/setup-python@v4
      with:
        python-version: "3.11.3"
        cache: "pip"
    - name: Freeze app with PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pyinstaller pyinstaller.spec
    - name: Create zip archive of frozen app
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: "zip"
        directory: "dist/focus-time"
        filename: ${{ inputs.frozen-archive-name }}
    - name: Upload zip archive
      uses: actions/upload-artifact@v3
      with:
        name: frozen-app
        path: ${{ inputs.frozen-archive-name }}
