name: "Build frozen app"
description: "Builds the app with PyInstaller, zips it and uploads it as artifact"
inputs:
  frozen-archive-name:
    description: "Name of the zip file to be created and published that contains the frozen application"
    default: "release.zip"
  dist-app-dir:
    description: "Relative path to the directory that contains the frozen app built by PyInstaller"
    default: "dist/focus-time"
  os:
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Python version
      uses: actions/setup-python@v4
      with:
        python-version: "3.11.3"
        cache: "pip"
    - name: Freeze app with PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pyinstaller pyinstaller.spec
      shell: ${{ inputs.os == 'windows-latest' && 'powershell' || 'bash' }}
    - name: Create zip archive of frozen app
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: "zip"
        directory:  ${{ inputs.dist-app-dir }}
        filename: ${{ inputs.frozen-archive-name }}
    - name: Upload zip archive
      uses: actions/upload-artifact@v3
      with:
        name: frozen-app
        path: ${{ format('{0}/{1}', inputs.dist-app-dir, inputs.frozen-archive-name) }}
