name: "Build frozen app"
description: "Builds the app with PyInstaller, zips it and uploads it as artifact"
inputs:
  dist-app-dir:
    description: "Relative path to the directory that contains the frozen app built by PyInstaller"
    default: "dist/focus-time"
  os:
    description: "Name of the runner's OS"
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Python version
      uses: actions/setup-python@v4
      with:
        python-version: "3.11.3"
        cache: "pip"
    - name: Freeze app with PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pyinstaller pyinstaller.spec
      shell: ${{ inputs.os == 'windows-latest' && 'powershell' || 'bash' }}
    - name: Compute Filename
      id: release_filename
      uses: actions/github-script@v4
      with:
        script: |
          const os = '${{ inputs.os }}';
          const ref = '${{ github.ref }}';
          const osName = os.replace('-latest', '');
          const refFinalPart = ref.split('/').pop();
          const filename = `focus-time-app-${osName}-${refFinalPart}.zip`;
          return filename;
        result-encoding: string
    - name: Create zip archive of frozen app
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: "zip"
        directory:  ${{ inputs.dist-app-dir }}
        filename: ${{ steps.release_filename.outputs.result }}
    - name: Upload zip archive
      uses: actions/upload-artifact@v3
      with:
        name: ${{ format('frozen-app-{0}', inputs.os) }}
        path: ${{ format('{0}/{1}', inputs.dist-app-dir, steps.release_filename.outputs.result) }}
        retention-days: 7
