name: CI/CD

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]
  workflow_dispatch:

jobs:
  ci:
    strategy:
      matrix:
        os: [ macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    # only run one job at a time, because the integration-test steps would otherwise interfere with each other
    concurrency: integration-test
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/build-windows-dnd-helper
        if: matrix.os == 'windows-latest'

      - uses: ./.github/actions/build-app
        with:
          os: ${{ matrix.os }}

      - name: Run integration tests
        # For now, we only run tests on Windows, because currently, on macOS, we cannot get the unattended installation
        # of the DND helper to work:
        # - On the stable macOS 12 runner OS, the Shortcuts app cannot be controlled using AppleScript, for unknown reasons
        # - On the still-in-beta macOS 13 runner OS, the Shortcut app can be controlled, but the  macOS 13 does not
        #   support AppleScript yet, see https://github.com/actions/runner-images/issues/7531
        if: matrix.os == 'windows-latest'
        run: |
          pytest tests
        env:
          CI: "1"
          OUTLOOK365_EMAIL: ${{ secrets.OUTLOOK365_EMAIL }}
          OUTLOOK365_PASSWORD: ${{ secrets.OUTLOOK365_PASSWORD }}

  cd:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download all releases
        uses: actions/download-artifact@v3
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: focus-time-*.zip
          prerelease: true
          generate_release_notes: true
