name: CI/CD

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  ci:
    strategy:
      matrix:
        os: [ macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/build-windows-dnd-helper
        if: matrix.os == 'windows-latest'

      - uses: ./.github/actions/build-app
        with:
          os: ${{ matrix.os }}

      - name: Run integration tests
        if: !startsWith(github.ref, 'refs/tags/')
        run: |
          pytest tests
        env:
          CI: "1"
          OUTLOOK365_EMAIL: ${{ secrets.OUTLOOK365_EMAIL }}
          OUTLOOK365_PASSWORD: ${{ secrets.OUTLOOK365_PASSWORD }}

  cd:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: [ ci ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download all releases
        uses: actions/download-artifact@v3
      # The download job creates a separate folder for every release, resulting in files such as
      # "frozen-app-macos-latest/focus-time-app-macos-v0.1.1.zip". Therefore, need a wide glob below for the
      # Release job
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "**/focus-time-*.zip"
          generate_release_notes: true
