name: CI/CD

on:
#  push:
#    branches: [ 'main' ]
#  pull_request:
#    branches: [ 'main' ]
  workflow_dispatch:

jobs:
  build-windows-dnd-helper:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64
      - name: Build DND helper
        run: |
          cd windows-dnd-msvc
          msbuild /property:Configuration=Release
          Move-item -Path 'x64/Release/windows-dnd.exe' -destination '../' -force
      - name: Upload DND helper executable
        uses: actions/upload-artifact@v3
        with:
          name: dnd-helper-windows-exe
          path: windows-dnd.exe

