name: macOS test

on:
  #  push:
  #    branches: [ 'main' ]
  #  pull_request:
  #    branches: [ 'main' ]
  workflow_dispatch:

jobs:
  build-windows-dnd-helper:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Register DND helper
        run: |
          # Temporary hack, as per https://github.com/actions/runner-images/issues/7531#issuecomment-1617707220
          sudo sqlite3 $HOME/Library/Application\ Support/com.apple.TCC/TCC.db "INSERT OR REPLACE INTO access VALUES('kTCCServiceAppleEvents','/usr/local/opt/runner/provisioner/provisioner',1,2,3,1,NULL,NULL,0,'com.apple.systemevents',X'fade0c000000003400000001000000060000000200000016636f6d2e6170706c652e73797374656d6576656e7473000000000003',NULL,1592919552);"
          sudo sqlite3 /Library/Application\ Support/com.apple.TCC/TCC.db "INSERT OR REPLACE INTO access VALUES('kTCCServiceAccessibility','/usr/local/opt/runner/provisioner/provisioner',1,2,4,1,NULL,NULL,0,'UNUSED',NULL,NULL,1592919552);"
          
          ./.github/macos-hacks/install-shortcut.sh
