name: macOS test

on:
  #  push:
  #    branches: [ 'main' ]
  #  pull_request:
  #    branches: [ 'main' ]
  workflow_dispatch:

jobs:
  build-windows-dnd-helper:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: Register DND helper
        run: |
          ./.github/macos-hacks/install-shortcut.sh
