name: macOS test shortcuts

on:
  workflow_dispatch:

jobs:
  build-windows-dnd-helper:
    runs-on: macos-latest
    steps:
      - name: Register DND helper
        run: |
          /usr/bin/shortcuts
          echo foo
          /usr/bin/shortcuts list
